### PR TITLE
Adding touch scroll

### PR DESCRIPTION
**Pull request by yourpalsonja**
Status: **Ready for Review**
Owner: @yourpalsonja
Reviewers: @jansepar @donnielrt @marlowpayne 

## Changes
- Added `-webkit-overflow-scrolling: touch` for a jank-free scrolling experience!

## Todos:
- [x] Engineer +1

## How to Test
- Open the test file and click on the image. (Got it hosted at [new-silk.surge.sh](new-silk.surge.sh) if you wanna check on your phone)

### CODE REVIEW

**Comment by marlowpayne** [comment]
Sooo deliciously smooth :+1:

**Comment by yourpalsonja** [comment]
66c15748-6208-11e5-9e14-b3e9b254b565

**Comment by donnielrt** [comment]
OOOooooOOOOooooo...thanks for the change @yourpalsonja!

We've got some spaces added, I'm assuming this was intentional?

**Comment by yourpalsonja** [comment]
@donnielrt actually spaces removed. ;)

**Comment by marlowpayne** [comment]
@donnielrt looks like whitespace changes are from trimming trailing whitespace

**Comment by donnielrt** [comment]
Awesome :)

**Pull request merged**
